### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by ghost** [LinusU/murmur128#2]
Hello.

I'm interested in using your library for hashing a simple object, specifically [here](https://github.com/Zaseth/bytearray-node/blob/master/src/AMF/AMF3.js#L385-L391).

Would your library be appropriate for my use case? I'm using md5 right now, and I'm looking for something faster, but also with less collision.

Thanks.

Edit:

I ran a simple 'benchmark' and came at around 0.660ms, since I use Buffer.from to convert the result to hex. MD5 is about 0.500ms. How can the performance be improved?

```js
console.time('murmur')
Buffer.from(murmur128(JSON.stringify({ id: 1 }))).toString('hex')
console.timeEnd('murmur')
```

**Comment by LinusU** [comment]
Keep in mind that `JSON.stringify({ a: 1, b: 2 })` and `JSON.stringify({ b: 2, a: 1 })` produces different input, if you really want to hash the objects you need to sort the keys first. That being said...

There are a lot of things happening in your example so it would be great if you could do some more measurements to see where the actual time is spent. Right now the steps are roughly:

- `JSON.stringify`
- `encodeUtf8(_)`
- Core murmur3 hash
- `Buffer.from(_)`
- `Buffer#toString('hex')`

If you can split up these steps and measure them separately it would greatly help 👍

**Comment by ghost** [comment]
Hello.

The object that I will be stringifying will always have the same keys, but just different values. I'm using a hash function as I can't use references.

JSON.stringify: `~0.090ms`
JSON.stringify+encodeUtf8: `~0.190ms` 
Murmur body+JSON.stringify: `~0.200ms`
Murmur tail+JSON.stringify: `~0.215ms`
Murmur finalize+JSON.stringify: `~0.185ms`
Buffer.from+JSON.stringify: `~0.255ms`
Buffer.from+JSON.stringify+Buffer.toString: `~0.270ms`

**I replaced `imul` with `Math.imul`**

Edit:

`murmurhash-native` seems much faster, returning hex as a default at around `~0.140ms`

**Comment by ghost** [comment]
Decided to go with `murmurhash-native`. Thanks.

**Comment by LinusU** [comment]
Yeah, I would guess that they have higher performance because it's a native module 👍
